steps:
  # Step 1: Build the Docker image for the Orders service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/orders-service', '-f', 'Dockerfile-orders', '.']
    dir: 'orders'  # Ensure the directory contains Dockerfile-orders

  # Step 2: Push the Orders Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/orders-service']

  # Step 3: Build the Docker image for the Login service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/login-service', '-f', 'Dockerfile-login', '.']
    dir: 'login'  # Ensure the directory contains Dockerfile-login

  # Step 4: Push the Login Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/login-service']

images:
  - 'gcr.io/$PROJECT_ID/orders-service'
  - 'gcr.io/$PROJECT_ID/login-service'

# Add a longer timeout (20 minutes) in case the build takes time
timeout: "1200s"  # 20 minutes

# Set logging options and specify logging to Cloud Logging only (optional)
options:
  logging: CLOUD_LOGGING_ONLY  # Log only to Cloud Logging

# Optionally, specify service account if needed (adjust service_account field)
# Uncomment and modify if you need to use a specific service account
# service_account: "[SERVICE_ACCOUNT_EMAIL]@PROJECT_ID.iam.gserviceaccount.com"
